# Kafka settings
spring:
  kafka:
    bootstrap-servers: kafka-server-1:9092,kafka-server-2:9092
    bootstrapAddress: localhost:29092

# MongoDB connection settings
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-database
#      username: my-username
#      password: my-password
