# Kafka settings
spring:
  kafka:
    bootstrap-servers: localhost:29092
# MongoDB connection settings
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-database
#      username: my-username
#      password: my-password
